In [1]:
import numpy as np

### loading data from sklearn

In [2]:
from sklearn import datasets
iris = datasets.load_iris() 
# iris.data contains the inputs (there are 150 of them and each one is a 4-dim vector)
# iris.target contains the outputs (classes 0,1,2)
# more information about this dataset: https://en.wikipedia.org/wiki/Iris_flower_data_set

In [4]:
iris.data.shape

(150, 4)

In [5]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### KNN classification

#### predict the class for a given testing point

In [3]:
X_training=iris.data # training inputs
Y_training = iris.target # training outputs
            
X_testing= X_training[1,:]            # set the test input

count_nb=15     # set the numbers of neighbours in KNN

# define the distance function
def dist(s,t):
    return np.sqrt(sum((s-t)*(s-t)))


# compute the distance from the test point of all training points
dt=np.zeros(len(X_training))
for i in range(len(X_training)):
    dt[i]=dist(X_testing,X_training[i])
    
# find the index of the closest neighbours
ind_NN=np.argsort(dt)[:count_nb]

# vote for the test output
# from statistics import mode
from scipy.stats import mode
Y_pred=mode(Y_training[ind_NN])[0]

print(Y_pred)



[0]


#### compute the training error

In [4]:
# training error
X_testing=X_training
Y_testing=Y_training
Y_pred=np.zeros(len(Y_testing))

err_count=0 # set the intial error count

for j in range(len(X_testing)):
    # compute the distance from the test point of all training points
    dt=np.zeros(len(X_training))
    for i in range(len(X_training)):
        dt[i]=dist(X_testing[j],X_training[i])

    # find the index of the closest neighbours
    ind_NN=np.argsort(dt)[:count_nb]

    # vote for the test output
    Y_pred[j]=mode(Y_training[ind_NN])[0]
    
    if Y_pred[j]!=Y_testing[j]:
        err_count=err_count+1    
    
err_perc=err_count/len(Y_testing)
print(err_perc)

    

0.013333333333333334


#### compute the test error for cross validation

In [6]:
# we consider 2-fold cross validation
# randomly divide the 150 training points into two groups with 75 each
sel_id_1=np.random.choice(150, 75, replace=False)
sel_id_2 = [x for x in range(150) if x not in sel_id_1]
X_training_1 = X_training[sel_id_1,:]
Y_training_1 = Y_training[sel_id_1]

X_training_2 = X_training[sel_id_2,:]
Y_training_2 = Y_training[sel_id_2]

In [7]:
X_testing=X_training_2
Y_testing=Y_training_2
Y_pred=np.zeros(len(Y_testing))

err_count=0 # set the intial error count

for j in range(len(X_testing)):
    # compute the distance from the test point of all training points
    dt=np.zeros(len(X_training_1))
    for i in range(len(X_training_1)):
        dt[i]=dist(X_testing[j],X_training_1[i])

    # find the index of the closest neighbours
    ind_NN=np.argsort(dt)[:count_nb]

    # vote for the test output
    Y_pred[j]=mode(Y_training_1[ind_NN])[0]
    
    if Y_pred[j]!=Y_testing[j]:
        err_count=err_count+1    
    
err_perc=err_count/len(Y_testing)
print(err_perc)

0.09333333333333334


#### Instead of repeating the same code a few times, it might be better to write a function for the common part 

In [8]:
def KNN_prediction(training_input, training_output, testing_input, testing_output, count_nb): 

    X_training=training_input
    Y_training=training_output

    X_testing=testing_input
    Y_testing=testing_output

    k=count_nb

    Y_pred=np.zeros(len(Y_testing))

    err_count=0 # set the intial error count

    for j in range(len(X_testing)):
        # compute the distance from the test point of all training points
        dt=np.zeros(len(X_training))
        for i in range(len(X_training)):
            dt[i]=dist(X_testing[j],X_training[i])

        # find the index of the closest neighbours
        ind_NN=np.argsort(dt)[:k]

        # vote for the test output
        Y_pred[j]=mode(Y_training[ind_NN])[0]

        if Y_pred[j]!=Y_testing[j]:
            err_count=err_count+1    

    err_perc=err_count/len(Y_testing)


    return err_perc

In [9]:
KNN_prediction(X_training_1, Y_training_1, X_training_2, Y_training_2, 5)

0.06666666666666667

In [10]:
KNN_prediction(X_training_2, Y_training_2, X_training_1, Y_training_1, 5)

0.05333333333333334

In [11]:
def selection_count_nb(data_in_1, data_out_1, data_in_2, data_out_2, count_nb_set):
    err=np.zeros(len(count_nb_set))
    for i in range(len(count_nb_set)):
        err1=KNN_prediction(data_in_1, data_out_1, data_in_2, data_out_2, count_nb_set[i])
        err2=KNN_prediction(data_in_2, data_out_2, data_in_1, data_out_1, count_nb_set[i])
        err[i]=err1+err2
    opt_in=np.argmin(err)

    return count_nb_set[opt_in]
        

In [14]:
selection_count_nb(X_training_1, Y_training_1, X_training_2, Y_training_2, np.array([1,3,4,5,6, 15,20]))

3

[2]
